/*
 Заполнить все таблицы БД vk данными (не больше 10-20 записей в каждой таблице)
 */
USE vk;

INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Jayne', 'Murazik', 'rosalia.wyman@example.net', '(277)844-75', '66e2f77e2fed758f5339d89714f71a2539fca4e3', '2020-09-04 17:36:54', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Brenna', 'Jaskolski', 'braeden71@example.org', '00999932297', '66bba7db5114c4ae1666c013e9b8c4dea2bc1e59', '1999-12-27 15:31:58', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Kallie', 'Hartmann', 'zboncak.glenna@example.org', '(489)327-18', '4902652415d526822db2fb990f76a36900964cd5', '2004-01-12 01:17:00', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Avery', 'VonRueden', 'lrolfson@example.com', '677-631-579', 'a635f7027f82aad72ba375da152be297e0ab64b1', '2008-11-23 07:36:17', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Ibrahim', 'Braun', 'kutch.vincenza@example.net', '129.766.977', '630267c0408e807e56d10d0924f4c6f84c457d65', '1983-07-10 03:19:22', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Pearlie', 'Hermiston', 'brionna47@example.com', '(070)062-42', '386328642ec1f14e8fe45e965e7490780585ba78', '1993-08-09 04:39:23', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Everette', 'Sipes', 'cmcclure@example.org', '872-458-606', 'ae75de9c5a8e9730a55a77cfda9c63ca87cb2128', '1998-09-05 12:33:49', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Nicholaus', 'Upton', 'kyleigh.kub@example.org', '1-102-801-0', '3085698c704964922b342194ad166e2698251fc7', '1975-09-05 21:11:09', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Eryn', 'Grant', 'salma50@example.net', '512.520.933', '21c6f8ebeb1cf50fc89fefa7be1f01e43b0f5c7d', '1989-06-03 04:32:43', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Barney', 'Bergnaum', 'stark.anjali@example.org', '272.613.441', '1466e09740d8a6adf3a72821f8558e0e058b80bc', '1982-04-07 23:00:27', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Sarina', 'Swift', 'rosendo06@example.com', '1-434-472-7', 'e3eccbcfc26965a263bfbac34355edbcf9d093d8', '2016-03-20 11:27:53', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Maximilian', 'Welch', 'austen.corwin@example.org', '1-300-152-6', '938706478092d9efccd0829cc1d728331c8c5673', '2000-04-04 11:53:02', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Hulda', 'Turcotte', 'yundt.ramona@example.com', '1-917-644-5', '17bc3a70bfc5862771cda545268ad5dd08e05ba7', '1978-03-13 12:42:49', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Ardella', 'Muller', 'albina.kshlerin@example.org', '1-461-670-8', 'de93422952a98f7aa6703475150095061f568730', '2014-08-21 22:32:18', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Jedidiah', 'Hane', 'jermain.mertz@example.net', '835.010.666', 'bcfb7c9839cb995c10131249373706d27d1f40f9', '2022-04-09 23:05:14', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Chase', 'Kautzer', 'fletcher61@example.org', '276.421.265', 'b2b45d031326dc227176b594232147db1f872d21', '1994-07-12 06:47:36', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Nikita', 'Ward', 'rice.uriah@example.org', '1-234-484-8', 'f5fd5c1ca9b2aadc39e5740adfab7b9a137c1a41', '2009-12-17 16:08:04', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Gussie', 'Bauch', 'reid.beatty@example.com', '281.289.850', 'fd8645ecc8fbdbb94ccc17e29801f783e2340e11', '2013-03-18 03:22:45', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Robin', 'Quigley', 'o\'conner.sheila@example.net', '04595108341', '39463e01677899cd78e1235c1a74c97ecaa3f351', '2002-06-04 22:15:11', NULL);
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `phone`, `password_hash`, `created_date`, `passport`) VALUES (NULL, 'Sydnee', 'Schneider', 'klocko.caroline@example.net', '689.473.230', 'd7637b6d41295a71820baee817a9d59625e540d5', '2006-11-26 11:10:58', NULL);

INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'Pink', 'Libero aut id et. Veniam rem eum atque voluptatibus. Sunt soluta error aut iusto.', 314);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'Maroon', 'Nobis voluptatem suscipit voluptas qui libero culpa in suscipit. Quia vitae maxime nihil porro at non. Aut nemo omnis exercitationem laborum. Et ut eveniet deleniti illum asperiores velit aut.', 315);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'Blue', 'Voluptate incidunt distinctio assumenda vel autem velit. Velit porro quis in. Vero quo hic dolorem dolore est.', 316);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'Lavender', 'Hic eum a quo eos consectetur sunt voluptatibus. Iure deserunt et sit minima. Nostrum debitis iusto voluptas numquam et dignissimos. Dicta blanditiis qui molestias.', 317);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'WhiteSmoke', 'Pariatur quidem voluptatem dolore in sit repellendus. Ea assumenda in eos vitae ab maiores qui. Exercitationem eum quo quae cupiditate eius officia temporibus. Adipisci aut ut perferendis beatae.', 318);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'Gainsboro', 'Voluptate numquam voluptatem et sed corrupti. Ratione et earum qui autem repellendus expedita. In accusantium vel dignissimos quae.', 319);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'Orange', 'Quia alias ab numquam impedit debitis inventore non. Minima velit libero sit voluptatem sit pariatur fugit nesciunt. Accusamus tenetur blanditiis perferendis fugit.', 320);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'Ivory', 'Inventore qui quis ducimus saepe rem. Officiis voluptas rerum mollitia expedita laudantium aliquam. Eius excepturi est id enim possimus esse.', 321);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'Gold', 'Molestiae odit explicabo sint ipsum illo enim ratione. Enim quia eos et ipsum praesentium beatae itaque quaerat. Exercitationem ad doloremque atque. Magnam accusantium qui amet et facilis aut.', 322);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'DeepSkyBlue', 'Aperiam aperiam autem autem veritatis eligendi id rerum. Non repellendus earum alias sint. Officiis quis inventore modi magnam nesciunt doloremque suscipit.', 323);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'FloralWhite', 'Qui doloremque nam maiores et magni qui ab. Pariatur minus numquam consectetur perferendis dolorum totam quia.', 324);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'Green', 'Itaque veniam nemo molestiae non consequatur dolores. Vel voluptatibus voluptatem adipisci minima provident error rerum provident. Doloremque ullam magni aperiam qui illo eos.', 325);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'Orchid', 'Harum aut qui dolorum architecto voluptatem maiores. Mollitia natus qui facilis fuga commodi. Fugiat ducimus tempore aut aut quos non.', 326);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'DarkGreen', 'Consequatur est laudantium qui libero nesciunt fugit. Nihil accusantium quam ipsum dignissimos molestiae aut. Quia atque nisi nihil magnam voluptates placeat incidunt.', 327);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'Aqua', 'Aut error quos error ut quia placeat. Voluptates voluptas rem animi et. Incidunt asperiores harum aliquam saepe expedita id earum recusandae.', 328);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'LightPink', 'Labore eos doloribus possimus nisi. Suscipit ex saepe quasi velit possimus neque. Rerum accusamus aut sapiente eum.', 329);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'DimGrey', 'Voluptas et perspiciatis tenetur iure. Nam eligendi adipisci aliquam eum et quia doloremque. Error occaecati enim ullam provident eos voluptate. Veritatis necessitatibus eum praesentium quos qui.', 330);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'SlateBlue', 'Nihil commodi quis et dolorem libero dignissimos et. Voluptas est ad nisi sapiente in fugiat aut. Atque dignissimos sint est et consequatur beatae. Maxime voluptatem id at facilis eaque.', 331);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'SlateGray', 'Est aspernatur est modi fuga voluptas ullam enim. Doloribus est delectus dolorum enim modi exercitationem aliquid. Quia maxime aut neque tenetur tempore.', 332);
INSERT INTO `communites` (`id`, `name`, `description`, `admin_id`) VALUES (NULL, 'DarkSlateGray', 'Voluptatum dicta quidem quis amet velit aut mollitia. Officia maiores repudiandae nihil sint repellat commodi. Iure dolores est molestiae nesciunt et odit. Aspernatur et atque tenetur doloribus.', 333);

INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('8', '314', '1981-04-18 05:30:17');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('1', '315', '2013-08-16 09:42:39');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('1', '314', '1989-03-01 10:31:28');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('3', '333', '2006-04-19 11:55:18');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('5', '320', '1997-06-11 17:42:52');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('3', '331', '1975-10-13 07:21:42');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('5', '321', '1973-07-11 18:34:19');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('4', '315', '2012-09-10 08:39:21');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('2', '330', '1985-12-28 01:58:02');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('9', '317', '1976-11-16 23:31:14');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('2', '331', '2006-03-17 15:52:29');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('7', '314', '1973-10-18 19:37:44');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('1', '316', '2010-03-27 01:17:50');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('6', '317', '1973-11-05 05:22:54');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('1', '317', '1978-02-01 12:21:47');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('9', '318', '1981-08-16 01:54:57');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('3', '332', '2019-09-29 04:44:22');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('9', '319', '1972-10-04 18:46:05');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('1', '318', '2004-12-15 16:14:46');
INSERT INTO `communities_users` (`community_id`, `user_id`, `created_at`) VALUES ('6', '320', '1983-01-05 21:26:12');

INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('314', '316', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('321', '318', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('327', '325', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('314', '327', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('314', '326', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('326', '318', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('326', '319', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('333', '328', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('314', '322', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('328', '317', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('324', '331', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('327', '333', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('329', '314', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('324', '332', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('328', '317', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('325', '319', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('326', '322', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('331', '333', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('332', '322', NULL);
INSERT INTO `friend_requests` (`from_user_id`, `to_user_id`, `accepted`) VALUES ('319', '333', NULL);

INSERT INTO `media` (`id`, `user_id`, `file_name`, `file_size`, `media_types_id`, `created_at`) VALUES (NULL, '316', 'Davon.jpg', '337802', 1, '1999-04-02 14:59:08');
INSERT INTO `media` (`id`, `user_id`, `file_name`, `file_size`, `media_types_id`, `created_at`) VALUES (NULL, '324', 'Dorian.txt', '2', 3, '2018-08-16 19:57:20');
INSERT INTO `media` (`id`, `user_id`, `file_name`, `file_size`, `media_types_id`, `created_at`) VALUES (NULL, '331', 'Scotty.avi', '2936912', 2, '1973-01-24 06:13:44');
INSERT INTO `media` (`id`, `user_id`, `file_name`, `file_size`, `media_types_id`, `created_at`) VALUES (NULL, '324', 'Theresia.mqu', '76200307', 2, '1986-08-05 15:48:44');
INSERT INTO `media` (`id`, `user_id`, `file_name`, `file_size`, `media_types_id`, `created_at`) VALUES (NULL, '319', 'Addison.txt', '0', 3, '1976-09-02 16:14:58');
INSERT INTO `media` (`id`, `user_id`, `file_name`, `file_size`, `media_types_id`, `created_at`) VALUES (NULL, '324', 'Ian.mov', '62662391', 2, '1972-05-31 21:25:57');
INSERT INTO `media` (`id`, `user_id`, `file_name`, `file_size`, `media_types_id`, `created_at`) VALUES (NULL, '314', 'Merritt.giff', '922038320', 1, '1984-04-14 00:13:32');
INSERT INTO `media` (`id`, `user_id`, `file_name`, `file_size`, `media_types_id`, `created_at`) VALUES (NULL, '328', 'Jeff.txt', '5663', 3, '2014-07-21 00:33:08');
INSERT INTO `media` (`id`, `user_id`, `file_name`, `file_size`, `media_types_id`, `created_at`) VALUES (NULL, '316', 'Aurore.txt', '1', 3, '2003-11-25 06:04:13');
INSERT INTO `media` (`id`, `user_id`, `file_name`, `file_size`, `media_types_id`, `created_at`) VALUES (NULL, '315', 'Domenico.jpg', '517', 1, '1984-06-17 20:34:52');

INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '315', 'consequatur', 'Voluptatibus voluptatum nam iure quibusdam aut ab. Ipsam corporis maiores sunt pariatur. Illum temporibus aliquid est qui expedita quo. Consequatur et beatae eligendi et.', 'http://www.koss.com/', '8');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '321', 'reiciendis', 'Minima fugiat commodi saepe rerum. Natus necessitatibus enim ipsam nostrum illum. Velit totam non ut et possimus.', 'http://pfeffer.com/', '9');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '316', 'voluptate', 'Provident saepe mollitia vel aut ut. Consequatur blanditiis assumenda quia in et voluptatibus alias. Laborum tempore consectetur omnis. Omnis non eos est cum cum.', 'http://www.gleason.org/', '1');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '321', 'sint', 'Quos enim ipsum illum excepturi quia. Voluptatem doloremque debitis aut optio accusamus eligendi. Est ea et excepturi eos. Quae voluptatem in atque eum nihil expedita modi.', 'http://www.satterfield.com/', '9');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '314', 'error', 'Quasi modi vel ad. Et eum illum repellat sunt qui. Eos ab et iusto et. Natus reprehenderit sit delectus nesciunt.', 'http://pagacbreitenberg.com/', '1');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '326', 'maxime', 'Porro at dicta culpa est omnis. Illum ipsa officiis maxime magnam accusantium.', 'http://schaefer.com/', '8');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '324', 'placeat', 'In sed fugit vero consequatur dolorem. Et voluptates harum repellendus laboriosam occaecati doloribus. Commodi itaque voluptatem quidem quia ipsa.', 'http://moore.info/', '1');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '328', 'velit', 'Quae ipsum animi totam ut est voluptatibus expedita. Officiis quos suscipit velit dolores iste optio. Voluptatem necessitatibus id cum sed expedita iusto quasi.', 'http://cummerata.com/', '4');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '328', 'rerum', 'Quis iure perferendis odio ab fuga eveniet eos. Omnis nam dolores aut cum modi. Soluta et aliquam non rem. Neque dolor sint deleniti voluptas quia.', 'http://paucekfeest.com/', '3');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '324', 'aut', 'Consequuntur mollitia tempora error eligendi velit sit. Et delectus quisquam veniam nam quia tenetur rem quia. Ut mollitia molestiae nobis eum. Omnis molestiae at nemo dolor. Similique labore exercitationem in nemo sit officia laborum est.', 'http://harber.com/', '2');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '322', 'illo', 'Maiores pariatur eius et quo. Laboriosam cumque fugiat laborum. Dolor numquam quia enim perferendis a quasi ut. Natus repellendus consectetur accusantium non beatae repellendus.', 'http://www.abshire.com/', '4');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '322', 'impedit', 'Dolores exercitationem sint ut esse voluptate est. Ad nulla tempora culpa est veritatis. Qui et minima molestias quo sunt vero odio. Sed autem alias explicabo sint cupiditate.', 'http://hammes.com/', '5');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '318', 'reiciendis', 'Minus ad illum nemo debitis dignissimos voluptas. Nobis ex facilis error fuga. Doloribus error nobis modi eveniet facilis. Quam illo nihil at officia velit ut esse asperiores.', 'http://www.bahringer.com/', '6');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '329', 'voluptas', 'Exercitationem voluptas ut voluptates veniam nisi dicta placeat fuga. Dolorum tenetur doloribus doloremque dolor ducimus temporibus nam. Delectus voluptatem blanditiis recusandae amet qui magni qui. Officia quis qui aperiam facilis facere est. Velit eum q', 'http://stroman.org/', '8');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '316', 'id', 'Quis dignissimos ea nam ut omnis tempora. Voluptatem id officiis quia et error architecto exercitationem. Aut voluptatibus sint aperiam repudiandae. Sit maxime dolorem eum omnis.', 'http://herzog.com/', '7');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '327', 'recusandae', 'Quia explicabo error perspiciatis ullam quo. Autem quisquam mollitia et quis est autem hic qui. Quia aut rerum corrupti ab cumque.', 'http://lehner.biz/', '4');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '317', 'rerum', 'Molestiae architecto nam alias earum id aut. Ratione alias sequi ea accusamus aut distinctio porro.', 'http://www.breitenbergohara.com/', '9');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '331', 'amet', 'Accusamus est maiores est. Recusandae facere assumenda dicta modi consequatur. Alias sint porro quia dolorem rerum autem eveniet. Consequuntur sed non quia. Minus aliquam excepturi voluptate est laborum.', 'http://www.watersrenner.com/', '5');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '319', 'totam', 'Voluptas cum nisi sapiente dolor. Qui soluta reprehenderit quis ut sed quidem repellat. Rerum nulla non est id.', 'http://ryan.com/', '5');
INSERT INTO `interest` (`id`, `user_id`, `name`, `description`, `link`, `image_id`) VALUES (NULL, '333', 'et', 'Qui et quaerat voluptas voluptatem quibusdam culpa voluptate. Quia aut ab ad eveniet illo est. Quod est totam laboriosam dolor fugit dolores.', 'http://www.gerhold.org/', '6');

INSERT INTO `media_types` (`id`, `name`) VALUES (NULL, 'chrt');
INSERT INTO `media_types` (`id`, `name`) VALUES (NULL, 'mdi');
INSERT INTO `media_types` (`id`, `name`) VALUES (NULL, 'z1');
INSERT INTO `media_types` (`id`, `name`) VALUES (NULL, 'webm');
INSERT INTO `media_types` (`id`, `name`) VALUES (NULL, 'mp4');
INSERT INTO `media_types` (`id`, `name`) VALUES (NULL, 'xul');
INSERT INTO `media_types` (`id`, `name`) VALUES (NULL, 'dd2');
INSERT INTO `media_types` (`id`, `name`) VALUES (NULL, 'der');
INSERT INTO `media_types` (`id`, `name`) VALUES (NULL, 'pre');
INSERT INTO `media_types` (`id`, `name`) VALUES (NULL, 'org');

INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 314, 322, 'Sequi quia asperiores quas dolorum. Aut eaque perspiciatis adipisci temporibus. Totam ea ex exercitationem dolorum qui.', 0, '1975-04-24 02:35:28', '1986-04-30 15:25:51');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 322, 314, 'Voluptates repudiandae iste molestias. Dicta quas ipsam quia est et voluptas dolorem.', 0, '1992-05-01 11:32:24', '2005-07-20 02:44:23');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 323, 333, 'Nisi dolorum accusantium ea est. Quo officiis possimus quia cumque facere molestiae. Deserunt unde modi est est accusamus. Animi necessitatibus et sed placeat.', 1, '1993-08-27 19:24:23', '1974-10-31 13:41:30');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 333, 323, 'Illo deleniti sint pariatur consequatur soluta sint facilis. Velit quo saepe aut voluptas quis.', 0, '1985-02-15 15:42:31', '1977-10-24 16:16:02');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 318, 325, 'Praesentium soluta enim eos. Enim et non ducimus ullam sed est autem. Itaque et deserunt dicta adipisci.', 1, '1992-02-02 04:50:31', '1995-02-27 04:37:55');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 319, 331, 'Dignissimos aspernatur quos beatae. Fuga eum dicta at culpa non ad vero.', 0, '1986-07-06 06:49:01', '1988-02-26 11:47:27');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 322, 328, 'Cumque vel eaque qui provident alias. Nihil est perspiciatis facilis officia nisi. Consequatur laudantium facere dolore ut. Aut quas quo eos quidem.', 1, '1977-01-31 03:08:02', '2004-05-22 05:43:53');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 328, 318, 'Ut ipsam numquam explicabo commodi dolorem. Ad corrupti exercitationem fugit eum debitis. Aliquam minus neque voluptatum recusandae alias tempora est. Et quia tenetur qui quibusdam atque sit ab.', 0, '1992-03-08 18:49:09', '1980-07-09 18:55:38');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 328, 322, 'Vero eius quaerat et iusto beatae. Vitae qui doloremque sint deserunt ea quibusdam voluptatem. Nobis porro id rerum sit eos quod. Ipsum ea mollitia doloremque ipsum.', 1, '2013-09-28 01:15:48', '2011-12-27 07:02:31');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 318, 319, 'Ipsum deserunt sit voluptas tempore harum deleniti a. Rerum suscipit vero harum autem quia ab sequi. Provident error nulla natus dolorum.', 0, '1986-11-25 17:18:37', '1992-11-07 10:26:26');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 333, 330, 'Tenetur fugit sunt veritatis ab. Ullam rem omnis rem nihil. Nemo illo quis est eos maiores ab et et. Mollitia dolores tempora itaque assumenda est ut.', 0, '2008-01-20 13:21:22', '2003-11-14 11:02:30');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 330, 320, 'Iste nostrum perferendis dolore iste qui. Natus omnis minima minus earum quisquam aliquam reiciendis tempora. Maiores hic ea fugit enim fuga assumenda qui.', 1, '2021-01-01 06:30:57', '2017-01-17 01:45:58');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 330, 318, 'Rem nesciunt voluptatem fuga quas sed eligendi iure. Aut ducimus harum optio perferendis nam non. Neque maxime architecto et aliquam optio labore sit.', 0, '1978-04-26 03:58:06', '2009-07-27 02:29:40');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 320, 319, 'Iste animi incidunt et. Eius voluptates repudiandae hic sunt perferendis. Veniam illo sunt laudantium omnis explicabo. Ipsam architecto culpa aspernatur ut est cupiditate ea.', 0, '1984-09-15 09:53:51', '2006-04-27 22:21:48');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 1, 333, 'Voluptas accusantium officiis reprehenderit similique sequi velit quia. Voluptatem et qui aspernatur. Culpa voluptatem amet nobis aut soluta et quia veritatis.', 0, '2000-10-10 06:16:04', '1977-11-30 05:50:06');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 2, 45, 'Facilis atque animi fugit amet et. Inventore ipsum non sunt harum nisi. Odit mollitia aut perspiciatis est impedit voluptas voluptatem.', 1, '2003-06-29 20:04:30', '2003-05-11 14:52:46');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 331, 55, 'Earum quia eum nobis quod doloremque deserunt excepturi. Veniam expedita voluptatum corrupti doloribus. Corrupti magnam adipisci porro fugit rem. Maiores consectetur molestiae ut maiores aut.', 0, '2004-12-05 22:13:14', '1999-01-09 09:43:55');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 55, 323, 'Doloribus dolor quia illum eum ducimus. Explicabo ut qui magnam. Dolor illo in cum beatae. Sit nulla nostrum aspernatur eos.', 1, '1976-09-20 23:47:47', '1984-08-11 06:16:51');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 324, 318, 'Delectus qui rerum ab placeat. Error in a ut porro et.', 0, '2018-08-08 23:28:37', '1987-10-25 14:03:45');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `txt`, `is_delivered`, `creates_at`, `updated_at`) VALUES (NULL, 318, 319, 'Qui fugit eligendi sequi accusantium ea laudantium quia. Voluptatem quae ut quis ipsam sed. Ut earum sapiente nihil officiis ut repudiandae voluptas.', 1, '2018-02-25 23:18:18', '1998-07-04 07:52:12');

INSERT INTO `post_access` (`id`, `type_access`) VALUES (DEFAULT, 'self');
INSERT INTO `post_access` (`id`, `type_access`) VALUES (DEFAULT, 'friend');
INSERT INTO `post_access` (`id`, `type_access`) VALUES (DEFAULT, 'close_friend');
INSERT INTO `post_access` (`id`, `type_access`) VALUES (DEFAULT, 'everyone');

INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (1, 1, 2);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (2, 4, 3);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (1, 1, 2);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (333, 7, 1);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (329, 3, 3);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (1, 13, 4);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (320, 12, 3);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (333, 1, 4);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (327, 6, 2);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (319, 7, 4);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (329, 8, 2);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (2, 6, 1);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (321, 11, 2);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (55, 9, 3);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (1, 11, 1);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (2, 7, 4);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (2, 13, 4);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (326, 9, 1);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (330, 5, 3);
INSERT INTO `post` (user_id, image_id, post_access_id) VALUES (2, 11, 3);

/*
 Заполнение таблицы profiles реализовал программой data_gen.py
 */
